name: recipes_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  dotted_border: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
